language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node-modules"
services:
  - postgresql
after_success: 
<<<<<<< HEAD
  - npm run coverage
  
=======
  - npm run coverage
>>>>>>> chore(ReadMe, .travis) travis integration
