language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
env:
  global:
  - NODE_ENV=test
before_script:
  - psql -c 'create database hellobookstest;' -U postgres
services:
  - postgresql
after_success: 
  - npm run coverage
